name: iOS

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "macos-latest", target: "ios" }
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Upgrade PIP
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Display Python version
        run: python --version

      - name: Display PIP version
        run: pip --version

      - name: Python requirements
        run: pip install -r requirements.txt

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: "3.20.0"

      - name: Build
        run: python make.py ${{ matrix.config.target }}-build

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact-${{ matrix.config.target }}
          path: build/${{ matrix.config.target }}

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: build/${{ matrix.config.target }}/dist.tar.gz
          asset_name: ${{ matrix.config.target }}.tar.gz
          asset_content_type: application/tar+gzip
